### ISSUE TITLE
RHEL boxes using FIPS causes MD5 function to fail

### ISSUE THREAD

**Issue by AfroThundr3007730** [akissa/clamavmirror#2]
There is a method to allow MD5 even though the security policy prevents it.

Basically the changes I made in Cisco-Talos/clamav-faq#86

**Comment by akissa** [comment]
With clamav's move to cloudflare DNS the script will required changes, the lookup of DNS IP's may now be obsolete.

**Comment by akissa** [comment]
Changes are reflected here aa37b4a8be53e1846a2b59cda2eb697c3918771b

**Comment by bdellegrazie** [comment]
@akissa the MD5 functions still need to be fixed regardless of the DNS changes I submitted previously.
I've raised PR #3 which directly copies @AfroThundr3007730's change.
If you merge this, could you please republish this to pypi?

**Comment by akissa** [comment]
Update released on pypi

**Comment by bdellegrazie** [comment]
@akissa Thank you!
